// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2OQEObjZNC5Zw2wpVMDadTQagc7v0gS0',
    appId: '1:569441220170:web:d5642a29de1b80f29f18b3',
    messagingSenderId: '569441220170',
    projectId: 'e-commerce-8416d',
    authDomain: 'e-commerce-8416d.firebaseapp.com',
    storageBucket: 'e-commerce-8416d.firebasestorage.app',
    measurementId: 'G-LPWYFVJTLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYi9ECFQ6zjFKRPawMAO6XDqJXbXs-Tqc',
    appId: '1:569441220170:android:b55f19f6e60b0c139f18b3',
    messagingSenderId: '569441220170',
    projectId: 'e-commerce-8416d',
    storageBucket: 'e-commerce-8416d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXONqssPC_c7UHCajgkCAO4ByNlJrNV0M',
    appId: '1:569441220170:ios:a28bb89caabe29c29f18b3',
    messagingSenderId: '569441220170',
    projectId: 'e-commerce-8416d',
    storageBucket: 'e-commerce-8416d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2OQEObjZNC5Zw2wpVMDadTQagc7v0gS0',
    appId: '1:569441220170:web:467e360d16e791709f18b3',
    messagingSenderId: '569441220170',
    projectId: 'e-commerce-8416d',
    authDomain: 'e-commerce-8416d.firebaseapp.com',
    storageBucket: 'e-commerce-8416d.firebasestorage.app',
    measurementId: 'G-ZM4313CMBY',
  );
}
